# _config.yml – Alembic-based setup
title: "Conversa AI Research"
description: "Corpus, bias studies and demonstrators for Spanish, Catalan, Basque & Galician dialogue research."
remote_theme: "daviddarnes/alembic@main"   # switch from ‘minima’ to Alembic

# Where the site lives
url: "https://conversa-ai.github.io"        # full domain
baseurl: ""                                 # leave empty when served from repo root
permalink: /:title/                         # clean URLs

# Header navigation (Alembic uses `navigation:` list of objects)
navigation:
  - text: "Corpus"
    url:  /corpus
  - text: "Bias & Models"
    url:  /bias
  - text: "Demonstrators"
    url:  /demos
  - text: "Publications"
    url:  /publications

# Collections (optional—enable blog posts if you want them)
collections:
  posts:
    output: true

# Recommended plugins for Alembic on GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme           # required for `remote_theme`

# Files/folders to ignore when the site builds
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock