# _config.yml — Minimal Mistakes version
title: "Conversa AI Research"
description: "Dialogue corpora, bias resources and demonstrators for Spanish, Catalan, Basque & Galician."
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

# Optional: site address (needed if you plan canonical URLs or SEO)
url: "https://conversa-ai.github.io"
baseurl: ""          # keep empty for org-site root

# --------------------------
# Primary navigation (top bar)
# --------------------------
navigation:
  - title: "Corpus"
    url:   /corpus/
  - title: "Bias & Models"
    url:   /bias/
  - title: "Demonstrators"
    url:   /demos/
  - title: "Publications"
    url:   /publications/

# --------------------------
# Plugins GitHub Pages allows
# --------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache     # required by Minimal Mistakes

# --------------------------
# Defaults: every page gets the “page” layout unless overridden
# --------------------------
defaults:
  - scope:
      path: ""
    values:
      layout: page
      author_profile: false

# --------------------------
# Build / housekeeping
# --------------------------
permalink: /:title/          # clean URLs without dates
paginate_path: /page:num/
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock